biblioteca/urls.py
from django.contrib import admin
from django.db import router
from django.urls import path, include

from rest_framework import routers

from livros.api import viewSets as livroviewSets

route = routers.DefaultRouter()

route.register('apiLivros', livroviewSets.LivroViewSet, basename="apiLivros")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('livros/', include("livros.urls",namespace="livros")),
    path('', include(route.urls))

]

livros/urls.py
from django.urls import path
from .views import CriarLivro, EditarLivro, ListaLivro, DeleteLivro

app_name = "livros"

urlpatterns = [
    path("", ListaLivro.as_view(), name="listar"),
    path("cadastrarLivro/", CriarLivro.as_view(), name="criar"),
    path("editarLivro/<int:pk>/", EditarLivro.as_view(), name="editar"),
    path("deletarLivro/<int:pk>/", DeleteLivro.as_view(), name="deletar")

]

livros/models.py
from django.db import models

# Create your models here.
class Livro(models.Model):
    titulo = models.CharField(max_length=255)
    autor = models.CharField(max_length=45)
    genero = models.CharField(max_length=45)
    qtd_paginas = models.IntegerField(verbose_name='Número de páginas')

    class Meta:
        ordering = ("titulo",)

    def __str__(self):
        return self.titulo

livros/views.py
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from .models import Livro


####### Create #########
class CriarLivro(CreateView):
    models = Livro
    fields = '__all__'
    template_name = 'livros/livro_create.html'
    success_url = reverse_lazy('livros:listar')

    def get_queryset(self):
        return Livro.objects.all()



####### Read #########
class ListaLivro(ListView):
    models = Livro
    template_name = 'livros/livro_list.html'
    

    def get_queryset(self):
        queryset = Livro.objects.all()
        return queryset


####### Update #########
class EditarLivro(UpdateView):
    models = Livro
    fields = '__all__'
    template_name = 'livros/livro_create.html'
    success_url = reverse_lazy('livros:listar')

    def get_queryset(self):
        return Livro.objects.all()


####### Delete #########
class DeleteLivro(DeleteView):
    models = Livro
    template_name ='livros/livro_delete.html'
    success_url = reverse_lazy('livros:listar')

    def get_queryset(self):
        queryset = Livro.objects.all()
        return queryset

livros/templates/livros/base.html
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block title %}{% endblock %}
    </title>
    {# Load the tag library #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-207667024-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-207667024-1');
       
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-P49K2QG');
    </script>


</head>

<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P49K2QG"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <header>
        {% block header %}{% endblock  %}
    </header>
    <main>
        {% block content %}
        {% endblock  %}
    </main>
</body>

</html>

livros/templates/livros/livro_create.html
{% extends 'livros/base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %}Cadastro de livros{% endblock  %}

{% block header %}

{% endblock  %}
{% block content %}

    <div class="row mb-4 mb-5">
        <div class="col-md-6 mx-auto">
            <h3 class="text-center">Cadastro de livros</h3>

            <hr>
            <form method="post" action="">
                {% csrf_token %}
                {% bootstrap_form form %}
                
                <button type="submit" class="btn btn-primary botao">Cadastrar</button>
                <a type="button" href = "{% url 'livros:listar'%}" class="btn btn-danger">Cancelar</a>

            </form>
        </div>

    </div>
{% endblock  %}

livros/templates/livros/livro_delete.html
{% extends 'livros/base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block content %}


    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Excluir registros</h3>
            <p class="lead">Confirme para excluir</p>

            <hr>
            <form method="post" action="">
                <p>Deseja excluir o registro: {{ object }} ?</p>

                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-danger">Excluir</button>
                <a type="button" href = "{% url 'livros:listar'%}" class="btn btn-primary">Cancelar</a>

            </form>
        </div>

    </div>

{% endblock %}

livros/templates/livros/livro_list.html
{% extends 'livros/base.html' %}


{% block title %}Lista de livros{% endblock %}

{% block header %}
    <div class="container">
        <h2>Livros</h2>
    </div>
{% endblock  %}

{% block content %}
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Autor</th>
                    <th>Genero</th>
                    <th>Páginas</th>
                    <th>Config</th>
                </tr>
            </thead>
            <tbody>
            {% for livro in livro_list %}
                <tr>
                    <td>{{livro.titulo}}</td>
                    <td>{{livro.autor}}</td>
                    <td>{{livro.genero}}</td>
                    <td>{{livro.qtd_paginas}}</td>
                    <td>
                        <a type="button" href="{% url 'livros:deletar' livro.id %}"class="btn btn-danger">Excluir</a>
                        <a type="button" href="{% url 'livros:editar' livro.id %}"class="btn btn-primary">Editar</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a type="button" href="{% url 'livros:criar' %}"class="btn btn-success">Cadastrar livro</a>
    </div>
      
{% endblock  %}